name: "Hello Actions"

description: "Greet your creator"

author: "azeezgames1@gmail.com"



inputs:

  MY_NAME:

    description: "Who to greet"

    required: true

    default: "Abdul-Azeez Akinyele"



runs:

  using: "docker"

  image: "Dockerfile"



branding:

  icon: "mic"

  color: "blue"
