name: A workflow for my Greetings file

on: push

jobs:

  build:

    name: Hello Creator action

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v1

      - uses: ./action-a

        with:

          MY_NAME: "Abdul"
